import Head from "next/head";
import { Preahvihear } from "next/font/google";
import Header from "@/components/Header";
import ListPost from "@/components/ListPost";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";

const poppins = Preahvihear({ subsets: ["latin"], weight: ["400"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>alphakahere Dev Blog</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className={`${poppins.className}`}>
					<Header />
					<main className="bg-gray-50 dark:bg-dark min-h-screen  py-14">
						<div className="app-container">
							<h1 className="bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-500 text-3xl font-bold">
								Tutoriels et articles
							</h1>
							<ListPost />
						</div>
					</main>
					<Footer />
				</div>
			</Layout>
		</>
	);
}
